/****************************************************************************
**
** Metadata for Pxserver generated by dumpcpp v5.9.2 using
** dumpcpp C:\Program Files\Petroleum Experts\IPM 10\pxserver.tlb
** from the type library C:\Program Files\Petroleum Experts\IPM 10\pxserver.tlb
**
****************************************************************************/

#define QAX_DUMPCPP_PXSERVER_NOINLINES
#include "pxserver.h"

using namespace Pxserver;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[49];
    char stringdata0[576];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 19, 0),
QT_MOC_LITERAL(1, 20, 9, 0),
QT_MOC_LITERAL(2, 30, 0, 0),
QT_MOC_LITERAL(3, 31, 4, 0),
QT_MOC_LITERAL(4, 36, 6, 0),
QT_MOC_LITERAL(5, 43, 4, 0),
QT_MOC_LITERAL(6, 48, 4, 0),
QT_MOC_LITERAL(7, 53, 15, 0),
QT_MOC_LITERAL(8, 69, 4, 0),
QT_MOC_LITERAL(9, 74, 6, 0),
QT_MOC_LITERAL(10, 81, 4, 0),
QT_MOC_LITERAL(11, 86, 4, 0),
QT_MOC_LITERAL(12, 91, 7, 0),
QT_MOC_LITERAL(13, 99, 6, 0),
QT_MOC_LITERAL(14, 106, 6, 0),
QT_MOC_LITERAL(15, 113, 11, 0),
QT_MOC_LITERAL(16, 125, 9, 0),
QT_MOC_LITERAL(17, 135, 14, 0),
QT_MOC_LITERAL(18, 150, 7, 0),
QT_MOC_LITERAL(19, 158, 14, 0),
QT_MOC_LITERAL(20, 173, 8, 0),
QT_MOC_LITERAL(21, 182, 8, 0),
QT_MOC_LITERAL(22, 191, 19, 0),
QT_MOC_LITERAL(23, 211, 12, 0),
QT_MOC_LITERAL(24, 224, 20, 0),
QT_MOC_LITERAL(25, 245, 12, 0),
QT_MOC_LITERAL(26, 258, 7, 0),
QT_MOC_LITERAL(27, 266, 13, 0),
QT_MOC_LITERAL(28, 280, 19, 0),
QT_MOC_LITERAL(29, 300, 8, 0),
QT_MOC_LITERAL(30, 309, 9, 0),
QT_MOC_LITERAL(31, 319, 6, 0),
QT_MOC_LITERAL(32, 326, 7, 0),
QT_MOC_LITERAL(33, 334, 25, 0),
QT_MOC_LITERAL(34, 360, 22, 0),
QT_MOC_LITERAL(35, 383, 13, 0),
QT_MOC_LITERAL(36, 397, 14, 0),
QT_MOC_LITERAL(37, 412, 21, 0),
QT_MOC_LITERAL(38, 434, 13, 0),
QT_MOC_LITERAL(39, 448, 16, 0),
QT_MOC_LITERAL(40, 465, 21, 0),
QT_MOC_LITERAL(41, 487, 7, 0),
QT_MOC_LITERAL(42, 495, 8, 0),
QT_MOC_LITERAL(43, 504, 11, 0),
QT_MOC_LITERAL(44, 516, 9, 0),
QT_MOC_LITERAL(45, 526, 7, 0),
QT_MOC_LITERAL(46, 534, 18, 0),
QT_MOC_LITERAL(47, 553, 11, 0),
QT_MOC_LITERAL(48, 565, 9, 0)
    },
    "Pxserver::IPxserver\0exception\0\0code\0source\0disc\0help\0propertyChanged\0name\0"
    "signal\0argc\0argv\0DoAbort\0CmdStr\0DoCmd2\0DoCmd2Async\0DoCommand\0DoCommandAsync\0"
    "GetBlob\0VariableString\0QString&\0BlobData\0GetErrorDescription\0lErrorNumber\0"
    "GetErrorDescription2\0GetLastError\0Product\0GetLastError2\0GetLastErrorMessage\0"
    "GetValue\0GetValue2\0IsBusy\0IsReady\0RecordingInsertBreakpoint\0RecordingInsertComment\0"
    "RecordingPlay\0RecordingStart\0__MIDL__IPxserver0000\0RecordingStop\0RecordingSuspend\0"
    "__MIDL__IPxserver0001\0SetBlob\0SetValue\0ValueString\0SetValue2\0control\0"
    "Pxserver::Document\0Interface 0\0IPxserver\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_Pxserver__IPxserver[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    27, 14, // methods
    1, 248, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 149, 2, 5,
    7, 1, 158, 2, 5,
    9, 3, 161, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 1, 168, 2, 9,
    14, 1, 171, 2, 9,
    15, 1, 174, 2, 9,
    16, 1, 177, 2, 9,
    17, 1, 180, 2, 9,
    18, 2, 183, 2, 9,
    22, 1, 188, 2, 9,
    24, 1, 191, 2, 9,
    25, 1, 194, 2, 9,
    27, 1, 197, 2, 9,
    28, 1, 200, 2, 9,
    29, 1, 203, 2, 9,
    30, 1, 206, 2, 9,
    31, 1, 209, 2, 9,
    32, 1, 212, 2, 9,
    33, 1, 215, 2, 9,
    34, 1, 218, 2, 9,
    35, 1, 221, 2, 9,
    36, 2, 224, 2, 9,
    38, 0, 229, 2, 9,
    39, 1, 230, 2, 9,
    41, 2, 233, 2, 9,
    42, 2, 238, 2, 9,
    44, 2, 243, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Int, QMetaType::QString, 13,
    QMetaType::Int, QMetaType::QString, 13,
    QMetaType::Int, QMetaType::QString, 13,
    QMetaType::Int, QMetaType::QString, 13,
    QMetaType::Int, QMetaType::QString, 13,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 20, 19, 21,
    QMetaType::QString, QMetaType::Int, 23,
    QMetaType::QString, QMetaType::Int, 23,
    QMetaType::Int, QMetaType::QString, 26,
    QMetaType::Int, QMetaType::QString, 26,
    QMetaType::QString, QMetaType::QString, 26,
    QMetaType::QString, QMetaType::QString, 19,
    QMetaType::QString, QMetaType::QString, 19,
    QMetaType::Int, QMetaType::QString, 26,
    QMetaType::Int, QMetaType::QString, 26,
    QMetaType::Int, QMetaType::QString, 13,
    QMetaType::Int, QMetaType::QString, 13,
    QMetaType::Int, QMetaType::QString, 13,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 13, 37,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, 40,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 20, 19, 21,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 19, 43,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 19, 43,

 // properties: name, type, flags
    45, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IPxserver::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_Pxserver__IPxserver, 0, 0, 0 }
};

void *IPxserver::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "Pxserver::IPxserver"))
        return static_cast<void*>(const_cast<IPxserver*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_Pxserver__Document[] = {

 // content:
    7, // revision
    46,  // classname
    1, 14, // classinfo
    27, 16, // methods
    0, 0, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    47, 48, 

// signal: name, argc, parameters, tag, flags
    1, 4, 151, 2, 5,
    7, 1, 160, 2, 5,
    9, 3, 163, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 1, 170, 2, 9,
    14, 1, 173, 2, 9,
    15, 1, 176, 2, 9,
    16, 1, 179, 2, 9,
    17, 1, 182, 2, 9,
    18, 2, 185, 2, 9,
    22, 1, 190, 2, 9,
    24, 1, 193, 2, 9,
    25, 1, 196, 2, 9,
    27, 1, 199, 2, 9,
    28, 1, 202, 2, 9,
    29, 1, 205, 2, 9,
    30, 1, 208, 2, 9,
    31, 1, 211, 2, 9,
    32, 1, 214, 2, 9,
    33, 1, 217, 2, 9,
    34, 1, 220, 2, 9,
    35, 1, 223, 2, 9,
    36, 2, 226, 2, 9,
    38, 0, 231, 2, 9,
    39, 1, 232, 2, 9,
    41, 2, 235, 2, 9,
    42, 2, 240, 2, 9,
    44, 2, 245, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Int, QMetaType::QString, 13,
    QMetaType::Int, QMetaType::QString, 13,
    QMetaType::Int, QMetaType::QString, 13,
    QMetaType::Int, QMetaType::QString, 13,
    QMetaType::Int, QMetaType::QString, 13,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 20, 19, 21,
    QMetaType::QString, QMetaType::Int, 23,
    QMetaType::QString, QMetaType::Int, 23,
    QMetaType::Int, QMetaType::QString, 26,
    QMetaType::Int, QMetaType::QString, 26,
    QMetaType::QString, QMetaType::QString, 26,
    QMetaType::QString, QMetaType::QString, 19,
    QMetaType::QString, QMetaType::QString, 19,
    QMetaType::Int, QMetaType::QString, 26,
    QMetaType::Int, QMetaType::QString, 26,
    QMetaType::Int, QMetaType::QString, 13,
    QMetaType::Int, QMetaType::QString, 13,
    QMetaType::Int, QMetaType::QString, 13,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 13, 37,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, 40,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 20, 19, 21,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 19, 43,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 19, 43,

    0 // eod
};

const QMetaObject Document::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_Pxserver__Document, 0, 0, 0 }
};

void *Document::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "Pxserver::Document"))
        return static_cast<void*>(const_cast<Document*>(this));
    return QAxObject::qt_metacast(_clname);
}

